INSERT INTO breeds (breedname) VALUES ("Affenpinscher");
INSERT INTO breeds (breedname) VALUES ("Afghan Hound");
INSERT INTO breeds (breedname) VALUES ("Airedale Terrier");
INSERT INTO breeds (breedname) VALUES ("Akita");
INSERT INTO breeds (breedname) VALUES ("Alaskan Klee Kai");
INSERT INTO breeds (breedname) VALUES ("Alaskan Malamute");
INSERT INTO breeds (breedname) VALUES ("American Bulldog");
INSERT INTO breeds (breedname) VALUES ("American English Coonhound");
INSERT INTO breeds (breedname) VALUES ("American Eskimo Dog");
INSERT INTO breeds (breedname) VALUES ("American Foxhound");
INSERT INTO breeds (breedname) VALUES ("American Pit Bull Terrier");
INSERT INTO breeds (breedname) VALUES ("American Staffordshire Terrier");
INSERT INTO breeds (breedname) VALUES ("American Water Spaniel");
INSERT INTO breeds (breedname) VALUES ("Anatolian Shepherd Dog");
INSERT INTO breeds (breedname) VALUES ("Appenzeller Sennenhunde");
INSERT INTO breeds (breedname) VALUES ("Australian Cattle Dog");
INSERT INTO breeds (breedname) VALUES ("Australian Kelpie");
INSERT INTO breeds (breedname) VALUES ("Australian Shepherd");
INSERT INTO breeds (breedname) VALUES ("Australian Terrier");
INSERT INTO breeds (breedname) VALUES ("Azawakh");
INSERT INTO breeds (breedname) VALUES ("Barbet");
INSERT INTO breeds (breedname) VALUES ("Basenji");
INSERT INTO breeds (breedname) VALUES ("Basset Hound");
INSERT INTO breeds (breedname) VALUES ("Beagle");
INSERT INTO breeds (breedname) VALUES ("Bearded Collie");
INSERT INTO breeds (breedname) VALUES ("Bedlington Terrier");
INSERT INTO breeds (breedname) VALUES ("Belgian Malinois");
INSERT INTO breeds (breedname) VALUES ("Belgian Sheepdog");
INSERT INTO breeds (breedname) VALUES ("Belgian Tervuren");
INSERT INTO breeds (breedname) VALUES ("Berger Picard");
INSERT INTO breeds (breedname) VALUES ("Bernedoodle");
INSERT INTO breeds (breedname) VALUES ("Bernese Mountain Dog");
INSERT INTO breeds (breedname) VALUES ("Bichon Frise");
INSERT INTO breeds (breedname) VALUES ("Black and Tan Coonhound");
INSERT INTO breeds (breedname) VALUES ("Black Mouth Cur");
INSERT INTO breeds (breedname) VALUES ("Black Russian Terrier");
INSERT INTO breeds (breedname) VALUES ("Bloodhound");
INSERT INTO breeds (breedname) VALUES ("Blue Lacy");
INSERT INTO breeds (breedname) VALUES ("Bluetick Coonhound");
INSERT INTO breeds (breedname) VALUES ("Boerboel");
INSERT INTO breeds (breedname) VALUES ("Bolognese");
INSERT INTO breeds (breedname) VALUES ("Border Collie");
INSERT INTO breeds (breedname) VALUES ("Border Terrier");
INSERT INTO breeds (breedname) VALUES ("Borzoi");
INSERT INTO breeds (breedname) VALUES ("Boston Terrier");
INSERT INTO breeds (breedname) VALUES ("Bouvier des Flandres");
INSERT INTO breeds (breedname) VALUES ("Boxer");
INSERT INTO breeds (breedname) VALUES ("Boykin Spaniel");
INSERT INTO breeds (breedname) VALUES ("Bracco Italiano");
INSERT INTO breeds (breedname) VALUES ("Briard");
INSERT INTO breeds (breedname) VALUES ("Brittany");
INSERT INTO breeds (breedname) VALUES ("Brussels Griffon");
INSERT INTO breeds (breedname) VALUES ("Bull Terrier");
INSERT INTO breeds (breedname) VALUES ("Bulldog");
INSERT INTO breeds (breedname) VALUES ("Bullmastiff");
INSERT INTO breeds (breedname) VALUES ("Cairn Terrier");
INSERT INTO breeds (breedname) VALUES ("Canaan Dog");
INSERT INTO breeds (breedname) VALUES ("Cane Corso");
INSERT INTO breeds (breedname) VALUES ("Cardigan Welsh Corgi");
INSERT INTO breeds (breedname) VALUES ("Catahoula Leopard Dog");
INSERT INTO breeds (breedname) VALUES ("Caucasian Shepherd Dog");
INSERT INTO breeds (breedname) VALUES ("Cavalier King Charles Spaniel");
INSERT INTO breeds (breedname) VALUES ("Cesky Terrier");
INSERT INTO breeds (breedname) VALUES ("Chesapeake Bay Retriever");
INSERT INTO breeds (breedname) VALUES ("Chihuahua");
INSERT INTO breeds (breedname) VALUES ("Chinese Crested");
INSERT INTO breeds (breedname) VALUES ("Chinese Shar-Pei");
INSERT INTO breeds (breedname) VALUES ("Chinook");
INSERT INTO breeds (breedname) VALUES ("Chow Chow");
INSERT INTO breeds (breedname) VALUES ("Clumber Spaniel");
INSERT INTO breeds (breedname) VALUES ("Cockapoo");
INSERT INTO breeds (breedname) VALUES ("Cocker Spaniel");
INSERT INTO breeds (breedname) VALUES ("Collie");
INSERT INTO breeds (breedname) VALUES ("Coton de Tulear");
INSERT INTO breeds (breedname) VALUES ("Curly-Coated Retriever");
INSERT INTO breeds (breedname) VALUES ("Dachshund");
INSERT INTO breeds (breedname) VALUES ("Dalmatian");
INSERT INTO breeds (breedname) VALUES ("Dandie Dinmont Terrier");
INSERT INTO breeds (breedname) VALUES ("Doberman Pinscher");
INSERT INTO breeds (breedname) VALUES ("Dogo Argentino");
INSERT INTO breeds (breedname) VALUES ("Dogue de Bordeaux");
INSERT INTO breeds (breedname) VALUES ("Dutch Shepherd");
INSERT INTO breeds (breedname) VALUES ("English Cocker Spaniel");
INSERT INTO breeds (breedname) VALUES ("English Foxhound");
INSERT INTO breeds (breedname) VALUES ("English Setter");
INSERT INTO breeds (breedname) VALUES ("English Springer Spaniel");
INSERT INTO breeds (breedname) VALUES ("English Toy Spaniel");
INSERT INTO breeds (breedname) VALUES ("Entlebucher Mountain Dog");
INSERT INTO breeds (breedname) VALUES ("Field Spaniel");
INSERT INTO breeds (breedname) VALUES ("Finnish Lapphund");
INSERT INTO breeds (breedname) VALUES ("Finnish Spitz");
INSERT INTO breeds (breedname) VALUES ("Flat-Coated Retriever");
INSERT INTO breeds (breedname) VALUES ("Fox Terrier");
INSERT INTO breeds (breedname) VALUES ("French Bulldog");
INSERT INTO breeds (breedname) VALUES ("German Pinscher");
INSERT INTO breeds (breedname) VALUES ("German Shepherd Dog");
INSERT INTO breeds (breedname) VALUES ("German Shorthaired Pointer");
INSERT INTO breeds (breedname) VALUES ("German Wirehaired Pointer");
INSERT INTO breeds (breedname) VALUES ("Giant Schnauzer");
INSERT INTO breeds (breedname) VALUES ("Glen of Imaal Terrier");
INSERT INTO breeds (breedname) VALUES ("Goldador");
INSERT INTO breeds (breedname) VALUES ("Golden Retriever");
INSERT INTO breeds (breedname) VALUES ("Goldendoodle");
INSERT INTO breeds (breedname) VALUES ("Gordon Setter");
INSERT INTO breeds (breedname) VALUES ("Great Dane");
INSERT INTO breeds (breedname) VALUES ("Great Pyrenees");
INSERT INTO breeds (breedname) VALUES ("Greater Swiss Mountain Dog");
INSERT INTO breeds (breedname) VALUES ("Greyhound");
INSERT INTO breeds (breedname) VALUES ("Harrier");
INSERT INTO breeds (breedname) VALUES ("Havanese");
INSERT INTO breeds (breedname) VALUES ("Ibizan Hound");
INSERT INTO breeds (breedname) VALUES ("Icelandic Sheepdog");
INSERT INTO breeds (breedname) VALUES ("Irish Red and White Setter");
INSERT INTO breeds (breedname) VALUES ("Irish Setter");
INSERT INTO breeds (breedname) VALUES ("Irish Terrier");
INSERT INTO breeds (breedname) VALUES ("Irish Water Spaniel");
INSERT INTO breeds (breedname) VALUES ("Irish Wolfhound");
INSERT INTO breeds (breedname) VALUES ("Italian Greyhound");
INSERT INTO breeds (breedname) VALUES ("Jack Russell Terrier");
INSERT INTO breeds (breedname) VALUES ("Japanese Chin");
INSERT INTO breeds (breedname) VALUES ("Japanese Spitz");
INSERT INTO breeds (breedname) VALUES ("Korean Jindo Dog");
INSERT INTO breeds (breedname) VALUES ("Karelian Bear Dog");
INSERT INTO breeds (breedname) VALUES ("Keeshond");
INSERT INTO breeds (breedname) VALUES ("Kerry Blue Terrier");
INSERT INTO breeds (breedname) VALUES ("Komondor");
INSERT INTO breeds (breedname) VALUES ("Kooikerhondje");
INSERT INTO breeds (breedname) VALUES ("Kuvasz");
INSERT INTO breeds (breedname) VALUES ("Labradoodle");
INSERT INTO breeds (breedname) VALUES ("Labrador Retriever");
INSERT INTO breeds (breedname) VALUES ("Lagotto Romagnolo");
INSERT INTO breeds (breedname) VALUES ("Lakeland Terrier");
INSERT INTO breeds (breedname) VALUES ("Lancashire Heeler");
INSERT INTO breeds (breedname) VALUES ("Leonberger");
INSERT INTO breeds (breedname) VALUES ("Lhasa Apso");
INSERT INTO breeds (breedname) VALUES ("Lowchen");
INSERT INTO breeds (breedname) VALUES ("Maltese");
INSERT INTO breeds (breedname) VALUES ("Maltese Shih Tzu");
INSERT INTO breeds (breedname) VALUES ("Maltipoo");
INSERT INTO breeds (breedname) VALUES ("Manchester Terrier");
INSERT INTO breeds (breedname) VALUES ("Mastiff");
INSERT INTO breeds (breedname) VALUES ("Miniature Pinscher");
INSERT INTO breeds (breedname) VALUES ("Miniature Schnauzer");
INSERT INTO breeds (breedname) VALUES ("Mudi");
INSERT INTO breeds (breedname) VALUES ("Mutt");
INSERT INTO breeds (breedname) VALUES ("Neapolitan Mastiff");
INSERT INTO breeds (breedname) VALUES ("Newfoundland");
INSERT INTO breeds (breedname) VALUES ("Norfolk Terrier");
INSERT INTO breeds (breedname) VALUES ("Norwegian Buhund");
INSERT INTO breeds (breedname) VALUES ("Norwegian Elkhound");
INSERT INTO breeds (breedname) VALUES ("Norwegian Lundehund");
INSERT INTO breeds (breedname) VALUES ("Norwich Terrier");
INSERT INTO breeds (breedname) VALUES ("Nova Scotia Duck Tolling Retriever");
INSERT INTO breeds (breedname) VALUES ("Old English Sheepdog");
INSERT INTO breeds (breedname) VALUES ("Otterhound");
INSERT INTO breeds (breedname) VALUES ("Papillon");
INSERT INTO breeds (breedname) VALUES ("Peekapoo");
INSERT INTO breeds (breedname) VALUES ("Pekingese");
INSERT INTO breeds (breedname) VALUES ("Pembroke Welsh Corgi");
INSERT INTO breeds (breedname) VALUES ("Petit Basset Griffon Vendeen");
INSERT INTO breeds (breedname) VALUES ("Pharaoh Hound");
INSERT INTO breeds (breedname) VALUES ("Plott");
INSERT INTO breeds (breedname) VALUES ("Pocket Beagle");
INSERT INTO breeds (breedname) VALUES ("Pointer");
INSERT INTO breeds (breedname) VALUES ("Polish Lowland Sheepdog");
INSERT INTO breeds (breedname) VALUES ("Pomeranian");
INSERT INTO breeds (breedname) VALUES ("Pomsky");
INSERT INTO breeds (breedname) VALUES ("Poodle");
INSERT INTO breeds (breedname) VALUES ("Portuguese Water Dog");
INSERT INTO breeds (breedname) VALUES ("Pug");
INSERT INTO breeds (breedname) VALUES ("Puggle");
INSERT INTO breeds (breedname) VALUES ("Puli");
INSERT INTO breeds (breedname) VALUES ("Pyrenean Shepherd");
INSERT INTO breeds (breedname) VALUES ("Rat Terrier");
INSERT INTO breeds (breedname) VALUES ("Redbone Coonhound");
INSERT INTO breeds (breedname) VALUES ("Rhodesian Ridgeback");
INSERT INTO breeds (breedname) VALUES ("Rottweiler");
INSERT INTO breeds (breedname) VALUES ("Saint Bernard");
INSERT INTO breeds (breedname) VALUES ("Saluki");
INSERT INTO breeds (breedname) VALUES ("Samoyed");
INSERT INTO breeds (breedname) VALUES ("Schipperke");
INSERT INTO breeds (breedname) VALUES ("Schnoodle");
INSERT INTO breeds (breedname) VALUES ("Scottish Deerhound");
INSERT INTO breeds (breedname) VALUES ("Scottish Terrier");
INSERT INTO breeds (breedname) VALUES ("Sealyham Terrier");
INSERT INTO breeds (breedname) VALUES ("Shetland Sheepdog");
INSERT INTO breeds (breedname) VALUES ("Shiba Inu");
INSERT INTO breeds (breedname) VALUES ("Shih Tzu");
INSERT INTO breeds (breedname) VALUES ("Siberian Husky");
INSERT INTO breeds (breedname) VALUES ("Silky Terrier");
INSERT INTO breeds (breedname) VALUES ("Skye Terrier");
INSERT INTO breeds (breedname) VALUES ("Sloughi");
INSERT INTO breeds (breedname) VALUES ("Small Munsterlander Pointer");
INSERT INTO breeds (breedname) VALUES ("Soft Coated Wheaten Terrier");
INSERT INTO breeds (breedname) VALUES ("Stabyhoun");
INSERT INTO breeds (breedname) VALUES ("Staffordshire Bull Terrier");
INSERT INTO breeds (breedname) VALUES ("Standard Schnauzer");
INSERT INTO breeds (breedname) VALUES ("Sussex Spaniel");
INSERT INTO breeds (breedname) VALUES ("Swedish Vallhund");
INSERT INTO breeds (breedname) VALUES ("Tibetan Mastiff");
INSERT INTO breeds (breedname) VALUES ("Tibetan Spaniel");
INSERT INTO breeds (breedname) VALUES ("Tibetan Terrier");
INSERT INTO breeds (breedname) VALUES ("Toy Fox Terrier");
INSERT INTO breeds (breedname) VALUES ("Treeing Tennessee Brindle");
INSERT INTO breeds (breedname) VALUES ("Treeing Walker Coonhound");
INSERT INTO breeds (breedname) VALUES ("Vizsla");
INSERT INTO breeds (breedname) VALUES ("Weimaraner");
INSERT INTO breeds (breedname) VALUES ("Welsh Springer Spaniel");
INSERT INTO breeds (breedname) VALUES ("Welsh Terrier");
INSERT INTO breeds (breedname) VALUES ("West Highland White Terrier");
INSERT INTO breeds (breedname) VALUES ("Whippet");
INSERT INTO breeds (breedname) VALUES ("Wirehaired Pointing Griffon");
INSERT INTO breeds (breedname) VALUES ("Xoloitzcuintli");
INSERT INTO breeds (breedname) VALUES ("Yorkipoo");
INSERT INTO breeds (breedname) VALUES ("Yorkshire Terrier");